"""Write launch SCREENSHOT_INDEX.md and evidence hash manifest."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
screens = ROOT / "docs" / "product" / "launch" / "screenshots"
run = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "product" / "launch" / "runs" / "latest"

rows = []
for png in sorted(screens.rglob("*.png")):
    rel = png.relative_to(ROOT).as_posix()
    rows.append(
        {
            "path": rel,
            "viewport": png.parent.name,
            "file": png.stem,
            "bytes": png.stat().st_size,
            "sha256": hashlib.sha256(png.read_bytes()).hexdigest(),
            "pass": png.stat().st_size > 2000,
        }
    )

idx = ROOT / "docs" / "product" / "launch" / "SCREENSHOT_INDEX.md"
lines = [
    "# Launch screenshot index",
    "",
    f"Total PNG files: **{len(rows)}**",
    "",
    "Generated by Playwright project `screenshots` (real PNG bytes, not LocalTunnel exports).",
    "",
    "| Path | Viewport | Capture | Bytes | Pass |",
    "|---|---|---|---:|:---:|",
]
for r in rows:
    status = "PASS" if r["pass"] else "FAIL"
    lines.append(f"| `{r['path']}` | {r['viewport']} | {r['file']} | {r['bytes']} | {status} |")
idx.write_text("\n".join(lines) + "\n", encoding="utf-8")

run.mkdir(parents=True, exist_ok=True)
(run / "screenshot-index-hash.json").write_text(
    json.dumps({"count": len(rows), "all_pass": all(r["pass"] for r in rows), "files": rows}, indent=2) + "\n",
    encoding="utf-8",
)
print("screenshots", len(rows), "all_pass", all(r["pass"] for r in rows))
